# Generated by Django 4.1 on 2022-09-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learner',
            options={},
        ),
    ]
