# Generated by Django 4.1 on 2022-09-18 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_learner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('word', models.CharField(max_length=20, unique=True)),
                ('meaning', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='learner',
            name='level',
            field=models.CharField(choices=[('BGR', 'Beginner'), ('ITD', 'Intermediate'), ('ADV', 'Advanced')], default='BGR', max_length=3),
        ),
    ]
