# Generated by Django 4.1 on 2022-09-18 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dailychallenge_alter_learner_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='learner',
            name='level',
            field=models.CharField(choices=[('BGR', 'Beginner'), ('ADV', 'Advanced'), ('ITD', 'Intermediate')], default='BGR', max_length=3),
        ),
    ]
