# Generated by Django 4.1 on 2022-09-18 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_dailychallenge_date_alter_learner_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, unique=True),
        ),
    ]
