# Generated by Django 4.1 on 2022-09-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_dailychallenge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='date',
            field=models.DateField(blank=True, default='2022-09-18', unique=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='level',
            field=models.CharField(choices=[('ADV', 'Advanced'), ('BGR', 'Beginner'), ('ITD', 'Intermediate')], default='BGR', max_length=3),
        ),
    ]
